spring.application.name=treeshopmanagingsystem
spring.datasource.url=jdbc:postgresql://localhost:5432/app
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
server.address=0.0.0.0
server.port=8080
